/* Processador local de Solicitação de Financeiro SPOA. */
const $ = (id) => document.getElementById(id);
const FILES = { dhr: null, siafi: null };
const OUT_HEADERS = ["Contrato","UF","Tomador","Ação","Abreviatura","UG Emitente","UG Favorecida","Nota de Empenho","Vinculação","Fonte","Categoria","Competência","Valor Original Total","RP","Saldo utilizado NE","Saldo remanescente NE"];
const ALIASES = {
  dhr: {
    operacao:["operacao","operação","operacao contrato","numero operacao"], dv:["dv","digito","dígito"], proposta:["proposta","proposta tgov","prop tgov","prop. tgov"], convenio:["convenio siafi","convênio siafi","convenio","convênio","numero instrumento","número instrumento","n instrumento","no instrumento"], tomador:["tomador","beneficiario","beneficiário","nome proponente","proponente"], municipio:["municipio","município","municipio beneficiado","município beneficiado"], uf:["uf","estado"], necessidade:["valor necessidade financeira","necessidade financeira","valor solicitado","valor da solicitacao","valor da solicitação","valor autorizado rp3","valor da parcela autorizado rp3","valor parcela autorizado rp3"], rp3:["saldo empenhado rp3","valor empenhado rp3","valor autorizado rp3","valor da parcela autorizado rp3"], empenhado:["valor empenhado rp2 e rp3","valor empenhado rp2 rp3","valor empenhado acumulado"]
  },
  siafi: {
    convenio:["numero do convenio","número do convênio","numero convenio","número convênio","convenio siafi","convênio siafi","informacao complementar","informação complementar","ne ccor informacao complementar","ne ccor informação complementar","ne cco informacao complementar"], info:["informacao complementar","informação complementar"], nota:["nota de empenho","ne ccor","ne cco","ne ccor nota","ne cco nota","ne"], fonte:["fonte recursos detalhada","fonte de recursos detalhada","fonte"], vinculacao:["vinculacao provavel","vinculação provável","vinculacao","vinculação"], favorecido:["ne ccor favorecido","ne cco favorecido","favorecido","beneficiario","beneficiário","cnpj favorecido"], processo:["numero processo","número processo","ne ccor num processo","ne ccor núm processo","ne cco num processo","ne cco núm processo","processo"], emp:["despesas empenhadas a liquidar controle emp","despesas empenhadas a liquidar","empenhadas a liquidar","30 despesas empenhadas a liquidar"], liq:["despesas liquidadas a pagar controle empenho","despesas liquidadas a pagar","liquidadas a pagar","32 despesas liquidadas a pagar"], rap:["restos a pagar a pagar proc e n proc","restos a pagar a pagar","restos a pagar","53 restos a pagar"]
  }
};

function clean(v){return String(v ?? "").trim()}
function norm(v){return clean(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]/g," ").replace(/\s+/g," ").trim()}
function digits(v){return clean(v).replace(/\D/g,"")}
function money(v){if(typeof v === "number"&&Number.isFinite(v)) return v; let s=clean(v).replace(/R\$/gi,"").replace(/\s/g,""); if(s.includes(",")&&s.includes("."))s=s.replace(/\./g,"").replace(",", ".");else s=s.replace(",", ".");return Number(s)||0}
function excelRow(ws,r){const range=XLSX.utils.decode_range(ws["!ref"]||"A1:A1"), row=[];for(let c=0;c<=range.e.c;c++)row[c]=ws[XLSX.utils.encode_cell({r,c})]?.v;return row}
function allRows(ws){const range=XLSX.utils.decode_range(ws["!ref"]||"A1:A1"), out=[];for(let r=0;r<=range.e.r;r++)out.push(excelRow(ws,r));return out}
function scoreHeader(row, aliases){return row.reduce((score,value)=>{const h=norm(value);return score+Object.values(aliases).reduce((n,list)=>n+(list.some(a=>norm(a)===h)?1:0),0)},0)}
function findTable(wb, kind){let best={score:-1};for(const name of wb.SheetNames){const ws=wb.Sheets[name], rows=allRows(ws);for(let r=0;r<Math.min(rows.length,30);r++){const nextScore=scoreHeader(rows[r+1]||[],ALIASES[kind]), headers=nextScore>0?rows[r].map((v,c)=>[v,rows[r+1]?.[c]].filter(x=>clean(x)).join(" ")):rows[r], score=scoreHeader(headers,ALIASES[kind]);if(score>best.score)best={score,name,header:r,headers,headerRows:nextScore>0?2:1,rows};}}if(best.score<2)throw new Error(`Não foi possível localizar os cabeçalhos da planilha ${kind==="dhr"?"do DHR":"do SIAFI"}. Confira se o arquivo contém a tabela indicada.`);return best}
function mapHeaders(headers,aliases){const map={};for(const [key,list] of Object.entries(aliases)){let best={score:0,index:undefined};headers.forEach((value,index)=>{const h=norm(value);if(!h)return;for(const item of list){const alias=norm(item);let score=0;if(alias===h)score=1000+alias.length;else if(alias.length>=7&&h.includes(alias))score=alias.length;else if(h.length>=7&&alias.includes(h))score=h.length;if(score>best.score)best={score,index};}});if(best.index!==undefined)map[key]=best.index;}return map}
function profileScore(values,test){const usable=values.filter(v=>clean(v)!=="");return usable.length?usable.filter(test).length/usable.length:0}
function inferByProfile(map,headers,rows,key,test,minScore=.85){if(map[key]!==undefined)return;const occupied=new Set(Object.values(map));const options=headers.map((_,index)=>({index,score:profileScore(rows.map(row=>row[index]),test)})).filter(x=>!occupied.has(x.index)).sort((a,b)=>b.score-a.score);if(options[0]&&options[0].score>=minScore&&(!options[1]||options[0].score-options[1].score>=.12))map[key]=options[0].index}
function inferMappings(map,headers,rows,kind){const sample=rows.slice(0,Math.min(rows.length,80));const states=new Set(["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"]);if(kind==="dhr"){inferByProfile(map,headers,sample,"convenio",v=>/^9\d{5}$/.test(digits(v)));inferByProfile(map,headers,sample,"uf",v=>states.has(norm(v)));inferByProfile(map,headers,sample,"tomador",v=>/\b(MUNICIPIO|PREFEITURA|SECRETARIA|ESTADO)\b/.test(norm(v)));inferByProfile(map,headers,sample,"proposta",v=>{const d=digits(v);return d.length>=8&&d.length<=10&&/^20\d{2}$/.test(d.slice(-4))});const used=new Set(Object.values(map));const financial=headers.map((_,index)=>({index,score:profileScore(sample.map(row=>row[index]),v=>typeof v==="number"&&v>=1000)})).filter(x=>!used.has(x.index)&&x.score>=.85);if(map.necessidade===undefined&&financial.length===1)map.necessidade=financial[0].index}else{inferByProfile(map,headers,sample,"convenio",v=>/^9\d{5}$/.test(digits(v)));inferByProfile(map,headers,sample,"nota",v=>/(?:\d+)?20\d{2}\s*NE\s*\d{6}(?!\d)/i.test(clean(v)));inferByProfile(map,headers,sample,"fonte",v=>/^1\d{9}$/.test(digits(v)));inferByProfile(map,headers,sample,"vinculacao",v=>/^\d{3}$/.test(digits(v)));inferByProfile(map,headers,sample,"favorecido",v=>/\b(MUNICIPIO|PREFEITURA|SECRETARIA)\b/.test(norm(v)));inferByProfile(map,headers,sample,"processo",v=>{const d=digits(v);return d.length>=8&&d.length<=10&&/^20\d{2}$/.test(d.slice(-4))});const numeric=headers.map((_,index)=>({index,score:profileScore(sample.map(row=>row[index]),v=>typeof v==="number"&&v>=0)})).filter(x=>x.score>=.85&&x.index>=Math.max(0,headers.length-6)).sort((a,b)=>a.index-b.index);if(numeric.length>=3){if(map.emp===undefined)map.emp=numeric[numeric.length-3].index;if(map.liq===undefined)map.liq=numeric[numeric.length-2].index;if(map.rap===undefined)map.rap=numeric[numeric.length-1].index}}return map}
function get(row,map,key){return map[key]===undefined?"":row[map[key]]}
function dataRows(table){return table.rows.slice(table.header+table.headerRows).filter(r=>r.some(v=>clean(v)!==""))}
function standardNE(v){const raw=clean(v).toUpperCase();const m=raw.match(/(20\d{2})\s*NE\s*(\d{6})(?!\d)/);return m?`${m[1]}NE${m[2]}`:raw.replace(/\s/g,"")}
function neYear(note){const m=standardNE(note).match(/(20\d{2})NE/);return m?Number(m[1]):9999}
function fonte(v){return clean(v)}
function proposalKeys(v){const d=digits(v);if(!d)return[];const out=[d];if(d.length>=8)out.push(d.slice(0,5)+d.slice(-4));return [...new Set(out)]}
function dhrKeys(item){const keys=new Set();for(const v of [item.convenio,item.proposta])for(const k of proposalKeys(v))keys.add(k);return [...keys].filter(k=>k.length>=5)}
function beneficiaryMatch(dhr, ne){const targets=[norm(dhr.tomador),norm(dhr.municipio)].filter(x=>x.length>=5);const source=norm(ne.favorecido);return source.length>=5&&targets.some(t=>source.includes(t)||t.includes(source))}
function contractMatch(dhr, ne){const convenio=digits(ne.convenio);return /^9\d{5}$/.test(convenio)&&!!dhr.convenioKey&&convenio===dhr.convenioKey}
function processMatch(dhr, ne){const processo=digits(ne.processo);return dhr.propostaKey.length>=5&&processo===dhr.propostaKey}
function selectCandidates(dhr, notes){
  const byContract=notes.filter(n=>contractMatch(dhr,n));
  if(byContract.length)return byContract;
  const byProcess=notes.filter(n=>processMatch(dhr,n));
  if(byProcess.length)return byProcess;
  return notes.filter(n=>{
    const hasContract=/^9\d{5}$/.test(digits(n.convenio));
    const hasProcess=digits(n.processo).length>=8;
    return !hasContract&&!hasProcess&&beneficiaryMatch(dhr,n);
  });
}
function formatContract(dhr){return clean(dhr.convenio)||clean(dhr.proposta)}
function orderCandidates(candidates, needed){
  const groups=new Map();
  for(const note of candidates){const year=neYear(note.nota);if(!groups.has(year))groups.set(year,[]);groups.get(year).push(note)}
  const years=[...groups.keys()].sort((a,b)=>a-b);const ordered=[];let remaining=needed, exhaustedEarlierYear=false;
  for(const year of years){const group=groups.get(year).slice();if(exhaustedEarlierYear)group.sort((a,b)=>a.saldo-b.saldo||a.ordem-b.ordem);ordered.push(...group);const total=group.reduce((sum,n)=>sum+n.saldo,0);if(remaining>total+.005){remaining-=total;exhaustedEarlierYear=true}else break;}
  return ordered;
}
function outputName(siafiTable){const title=clean(siafiTable.rows[0]?.[0]);const m=title.match(/(\d{2})\D+(\d{2})\D+(\d{4})/);return m?`Planilha_de_Financeiro_a_SPOA_${m[1]}_${m[2]}_${m[3]}.xlsx`:"Planilha_de_Financeiro_a_SPOA.xlsx"}
function selectedStartYear(){return document.querySelector('input[name="startYear"]:checked')?.value||"2025"}
function makeStyle(header=false){return {font:{bold:header},fill:header?{patternType:"solid",fgColor:{rgb:"C8C8C8"}}:undefined,alignment:{horizontal:header?"center":"left",vertical:"center"},border:{top:{style:"thin",color:{rgb:"000000"}},bottom:{style:"thin",color:{rgb:"000000"}},left:{style:"thin",color:{rgb:"000000"}},right:{style:"thin",color:{rgb:"000000"}}}}}
function styleTable(ws, headers, moneyColumns=[]){const range=XLSX.utils.decode_range(ws["!ref"]||"A1:A1");for(let c=0;c<=range.e.c;c++){const h=XLSX.utils.encode_cell({r:0,c});ws[h].s=makeStyle(true);ws["!cols"]=(ws["!cols"]||[]);ws["!cols"][c]={wch:Math.min(Math.max(String(headers[c]||"").length+3,13),28)};}for(let r=1;r<=range.e.r;r++)for(let c=0;c<=range.e.c;c++){const a=XLSX.utils.encode_cell({r,c});if(!ws[a])ws[a]={t:"s",v:""};ws[a].s=makeStyle(false);if(moneyColumns.includes(c))ws[a].z='#,##0.00';}}
function styleSourceHeaders(ws, rows){const range=XLSX.utils.decode_range(ws["!ref"]||"A1:A1");for(const r of rows)for(let c=0;c<=range.e.c;c++){const a=XLSX.utils.encode_cell({r,c});if(ws[a])ws[a].s=makeStyle(true)}}
function addLog(log, contract, tomador, value, keys, reason){log.push([contract,tomador,value,keys,reason])}
function friendlyKeys(req){const keys=[];if(req.convenioKey)keys.push(`instrumento ${formatContract(req)}`);if(req.propostaKey)keys.push(`proposta ${clean(req.proposta)}`);if(clean(req.tomador))keys.push(`proponente ${clean(req.tomador)}`);if(clean(req.municipio))keys.push(`município ${clean(req.municipio)}`);return keys.join("; ")||"sem chave identificável"}
function favouredName(row,map){const primary=clean(get(row,map,"favorecido"));const index=map.favorecido;if(index===undefined)return primary;const next=clean(row[index+1]);return /^\d{11,14}$/.test(digits(primary))&&next?next:primary}

async function process(){
  const dhrBook=XLSX.read(await FILES.dhr.arrayBuffer(),{type:"array",raw:true,cellStyles:true});
  const siafiBook=XLSX.read(await FILES.siafi.arrayBuffer(),{type:"array",raw:true,cellStyles:true});
  const dhrTable=findTable(dhrBook,"dhr"), siafiTable=findTable(siafiBook,"siafi");
  const dhrMap=inferMappings(mapHeaders(dhrTable.headers,ALIASES.dhr),dhrTable.headers,dhrTable.rows.slice(dhrTable.header+dhrTable.headerRows),"dhr"), siafiMap=inferMappings(mapHeaders(siafiTable.headers,ALIASES.siafi),siafiTable.headers,siafiTable.rows.slice(siafiTable.header+siafiTable.headerRows),"siafi");
  for(const required of ["convenio","tomador","uf","necessidade"])if(dhrMap[required]===undefined)throw new Error(`A coluna indispensável '${required}' não foi reconhecida na planilha do DHR.`);
  for(const required of ["nota","fonte","emp","rap"])if(siafiMap[required]===undefined)throw new Error(`A coluna indispensável '${required}' não foi reconhecida na planilha do SIAFI.`);
  const requests=dhrTable.rows.slice(dhrTable.header+dhrTable.headerRows).filter(r=>r.some(v=>clean(v)!=="")).map(r=>{const item={operacao:get(r,dhrMap,"operacao"),dv:get(r,dhrMap,"dv"),proposta:get(r,dhrMap,"proposta"),convenio:get(r,dhrMap,"convenio"),tomador:get(r,dhrMap,"tomador"),municipio:get(r,dhrMap,"municipio"),uf:get(r,dhrMap,"uf"),valor:money(get(r,dhrMap,"necessidade")),rp3:money(get(r,dhrMap,"rp3")),empenhado:money(get(r,dhrMap,"empenhado"))};item.convenioKey=digits(item.convenio);item.propostaKey=digits(item.proposta);item.keys=dhrKeys(item);return item}).filter(x=>x.valor>0);
  const anoAtual=new Date().getFullYear(), anoInicial=selectedStartYear();
  const rawNotes=siafiTable.rows.slice(siafiTable.header+siafiTable.headerRows).filter(r=>r.some(v=>clean(v)!=="")).map((r,ordem)=>{const nota=standardNE(get(r,siafiMap,"nota")), ano=neYear(nota), rap=money(get(r,siafiMap,"rap")), emp=money(get(r,siafiMap,"emp"));return {nota,ano,convenio:clean(get(r,siafiMap,"convenio")),fonte:fonte(get(r,siafiMap,"fonte")),vinculacao:clean(get(r,siafiMap,"vinculacao")),favorecido:favouredName(r,siafiMap),info:clean(get(r,siafiMap,"info")),processo:clean(get(r,siafiMap,"processo")),saldo:ano<anoAtual?rap:emp,ordem};}).filter(x=>x.nota&&x.saldo>0&&x.ano<=anoAtual&&(anoInicial==="all"||x.ano>=Number(anoInicial)));
  const notes=new Map();for(const n of rawNotes){const old=notes.get(n.nota);if(old)old.saldo+=n.saldo;else notes.set(n.nota,n)}const noteList=[...notes.values()].sort((a,b)=>neYear(a.nota)-neYear(b.nota)||a.ordem-b.ordem);
  const output=[OUT_HEADERS], log=[["Contrato","Tomador","Valor pendente","Chaves consultadas","Inconsistência"]], used=new Map();let allocations=0;
  for(const req of requests){let remaining=req.valor, found=false;const candidates=orderCandidates(selectCandidates(req,noteList),req.valor);
    if(!candidates.length){addLog(log,formatContract(req),clean(req.tomador),remaining,friendlyKeys(req),"Nenhuma Nota de Empenho vinculável: o SIAFI não apresentou correspondência para as chaves indicadas.");continue;}
    for(const note of candidates){if(remaining<=0.005)break;const current=used.has(note.nota)?used.get(note.nota):note.saldo;if(current<=0)continue;const allocation=Math.min(current,remaining), rp=req.rp3>0?3:2;output.push([formatContract(req),clean(req.uf),clean(req.tomador),"00TI","FNHIS SUB 50","560015","560018",note.nota,note.vinculacao,note.fonte,"D",neYear(note.nota)===2025?2:3,req.valor,rp,allocation,current-allocation]);used.set(note.nota,current-allocation);remaining-=allocation;allocations++;found=true;}
    if(remaining>0.005)addLog(log,formatContract(req),clean(req.tomador),remaining,friendlyKeys(req),found?"Saldo insuficiente nas Notas de Empenho vinculadas.":"Nenhuma Nota de Empenho com saldo disponível.");
  }
  if(!requests.length)addLog(log,"","",0,"coluna de necessidade financeira",`Nenhuma linha com valor positivo foi identificada na coluna “${dhrTable.headers[dhrMap.necessidade]}”.`);
  const textOrder=(a,b)=>String(a??"").localeCompare(String(b??""),"pt-BR",{sensitivity:"base",numeric:true});const orderedOutput=[output[0],...output.slice(1).sort((a,b)=>textOrder(a[1],b[1])||textOrder(a[2],b[2])||textOrder(a[7],b[7]))];
  const wb=XLSX.utils.book_new(), ws=XLSX.utils.aoa_to_sheet(orderedOutput), sourceWs=siafiBook.Sheets[siafiTable.name];styleTable(ws,OUT_HEADERS,[12,14,15]);XLSX.utils.book_append_sheet(wb,ws,"ajustada CORH");XLSX.utils.book_append_sheet(wb,sourceWs,"SALDOS DE EMPENHO");if(log.length>1){const logWs=XLSX.utils.aoa_to_sheet(log);styleTable(logWs,log[0],[2]);XLSX.utils.book_append_sheet(wb,logWs,"LOG");}
  XLSX.writeFile(wb,outputName(siafiTable),{cellStyles:true});
  return {requests:requests.length,notes:noteList.length,allocations,issues:log.length-1,dhrSheet:dhrTable.name,siafiSheet:siafiTable.name,anoInicial};
}
function updateButton(){ $("processButton").disabled=!(FILES.dhr&&FILES.siafi) }
function pick(type,event){FILES[type]=event.target.files[0]||null;$(type+"Name").textContent=FILES[type]?FILES[type].name:"Selecionar arquivo .xlsx";$("status").textContent=FILES.dhr&&FILES.siafi?"Arquivos anexados. Você já pode gerar a planilha.":"Anexe os dois arquivos para habilitar o processamento.";updateButton()}
$("dhrFile").addEventListener("change",e=>pick("dhr",e));$("siafiFile").addEventListener("change",e=>pick("siafi",e));
$("processButton").addEventListener("click",async()=>{try{$("processButton").disabled=true;$("status").textContent="Lendo os arquivos e distribuindo os saldos por Nota de Empenho…";const r=await process();const logText=r.issues?` Foram registradas ${r.issues} inconsistência(s); consulte a aba LOG do arquivo baixado.`:" Não foram registradas inconsistências.";const periodo=r.anoInicial==="all"?"todos os anos disponíveis":`de ${r.anoInicial} a ${new Date().getFullYear()}`;$("status").textContent=`Processamento concluído. O arquivo foi baixado.${logText}`;$("details").hidden=false;$("details").innerHTML=`<h2>Resumo do processamento</h2><ul><li>${r.requests} solicitação(ões) financeira(s) identificada(s) na aba “${r.dhrSheet}”.</li><li>${r.notes} Nota(s) de Empenho com saldo identificada(s) na aba “${r.siafiSheet}”, considerando ${periodo}.</li><li>${r.allocations} distribuição(ões) gerada(s) na Planilha de Financeiro à SPOA.</li><li>Para outro ciclo, anexe dois novos arquivos.</li></ul>`;}catch(e){console.error(e);$("status").textContent=`Não foi possível processar: ${e.message}`;}finally{$("processButton").disabled=!(FILES.dhr&&FILES.siafi)}});

